name: workflow
channels:
  - conda-forge
dependencies:
  - pandas
  - pudb
  - joblib
  - wrf-python
  - wget
  - numpy
  - python=3.11.14
  - pyyaml
  - f90nml
  - salem
  - rasterio
  - matplotlib
  - ipykernel
  - cartopy
  - gh
