sim_hrs: 30
template_dir: /glade/u/home/jaredlee/tools/python/setup_wps_wrf/wps_wrf_workflow/templates/fasteddy_nm
wps_ins_dir: /glade/u/home/jaredlee/programs/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/jaredlee/programs/WRF-4.6
wps_run_dir: /glade/derecho/scratch/jaredlee/workflow/fasteddy_nm/wps
wrf_run_dir: /glade/derecho/scratch/jaredlee/workflow/fasteddy_nm/wrf
grib_dir: /glade/derecho/scratch/jaredlee/data/hrrr
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: True
hrrr_native: True
get_icbc: True
do_geogrid: True
do_ungrib: True
do_avg_tsfc: True
use_tavgsfc: True
do_metgrid: True
do_real: True
do_wrf: True
archive: False