sim_hrs: 30
template_dir: YOURPATH/workflow/templates/WRF_1Dom1km
wps_ins_dir: YOURPATH/WPS-4.6-dmpar-casper
wrf_ins_dir: YOURPATH/WRF-4.6
wps_run_dir: /glade/derecho/scratch/YOURUSERNAME/workflow/UM_WRF_1Dom1km/wps
wrf_run_dir: /glade/derecho/scratch/YOURUSERNAME/workflow/UM_WRF_1Dom1km/wrf
grib_dir: /glade/derecho/scratch/YOURUSERNAME/data/hrrr
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: True 
hrrr_native: True
get_icbc: True
do_geogrid: True
do_ungrib: True
do_avg_tsfc: True
use_tavgsfc: True
do_metgrid: True
do_real: True
do_wrf: True
archive: False
