sim_hrs: 30
template_dir: /glade/u//home/ljaeger/wrf-run/templates/WRF_1Dom1km/fire_24332880
wps_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WRF-4.6
wps_run_dir: /glade/derecho/scratch/ljaeger/workflow/UM_WRF_1Dom1km/wps
wrf_run_dir: /glade/derecho/scratch/ljaeger/workflow/UM_WRF_1Dom1km/wrf
grib_dir: /glade/derecho/scratch/ljaeger/data/hrrr
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: true
hrrr_native: true
get_icbc: true
do_geogrid: true
do_ungrib: true
do_avg_tsfc: true
use_tavgsfc: true
do_metgrid: true
do_real: true
do_wrf: true
archive: false
exp_name: fire_24332880
exp_wrf_only: false
