sim_hrs: 24
template_dir: /glade/work/ljaeger/workflow/templates
wps_ins_dir: /glade/u/home/ljaeger/programs/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/ljaeger/programs/WRF-4.6
wps_run_dir: /glade/derecho/scratch/ljaeger/workflow/wps
wrf_run_dir: /glade/derecho/scratch/ljaeger/workflow/wrf
grib_dir: /glade/derecho/scratch/ljaeger/data/hrrr
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: True
hrrr_native: True
get_icbc: True
do_geogrid: False
do_ungrib: True
do_avg_tsfc: True
use_tavgsfc: True
do_metgrid: True
do_real: True
do_wrf: True
do_upp: False
upp_yaml: /glade/work/ljaeger/workflow/templates/run_upp.yaml
upp_domains:
  - '1'
archive: False
